# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master
- dev/*

pool:
  vmImage: 'macos-latest'

variables:
  iOSRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_iOS_v3_0_0_FULL.zip?_ga=2.79185814.368877217.1583320605-5559409.1503304822'
  MacRTCSDK: 'https://download.agora.io/sdk/release/Agora_Native_SDK_for_Mac_v3_0_0_FULL.zip?_ga=2.78400662.368877217.1583320605-5559409.1503304822'

jobs:

- template: Android/azure-templates/build-android.yml
  parameters:
    project: 'Android'
    module: 'sample-switch-external-video'
    name: 'SwitchVideoInputAndroid'

- template: Android/azure-templates/build-android.yml
  parameters:
    project: 'Android'
    module: 'sample-video-encrypt'
    name: 'VideoEncryptionAndroid'

- template: Android/azure-templates/build-android.yml
  parameters:
    project: 'Android'
    module: 'sample-custom-render'
    name: 'CustomRendererAndroid'
    
 - template: Android/azure-templates/build-android.yml
  parameters:
    project: 'Android'
    module: 'sample-push-video'
    name: 'PushVideo'

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraCustomMediaDevice'
    workingDirectory: 'iOS&macOS/Agora-Custom-Media-Device'
    scheme: 'Agora-Custom-Media-Device'
    sdkurl: $(iOSRTCSDK)

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraPluginRawDataAPIiOSObjectiveC'
    workingDirectory: 'iOS&macOS/Agora-Plugin-Raw-Data-API-Objective-C'
    scheme: 'Agora-Plugin-Raw-Data-API-iOS-Objective-C'
    sdkurl: $(iOSRTCSDK)
    
- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraScreenSharing'
    workingDirectory: 'iOS&macOS/Agora-Screen-Sharing'
    scheme: 'Agora-Plugin-Raw-Data-API-iOS-Objective-C'
    sdkurl: $(iOSRTCSDK)

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraVideoSource'
    workingDirectory: 'iOS&macOS/Agora-Video-Source'
    scheme: 'Agora-Screen-Sharing'
    sdkurl: $(iOSRTCSDK)

- template: iOS&macOS/build-template/build-ios.yml
  parameters:
    displayName: 'AgoraVideoWithARKit'
    workingDirectory: 'iOS&macOS/Agora-Video-With-ARKit'
    scheme: 'Agora-Video-With-ARKit'
    sdkurl: $(iOSRTCSDK)
